apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
data:
  SPRING_PROFILES_ACTIVE: kube
  MONGODB_URI: mongodb+srv://root:root@cluster0.yuincts.mongodb.net/?retryWrites=true&w=majority



