spring:
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.yuincts.mongodb.net/?retryWrites=true&w=majority
      database: clients
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

app:
  jwtSecret: SecretKey
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 1200000

rabbitmq:
  exchanges:
    clients: clients.exchange
  queues:
    clients: clients.queue
    email: email.queue
  routing-keys:
    clients: clients.routing-key
    email: email.routing-key