version: '3.3'
services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
        - backend
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - backend
volumes:
    postgres:
    pgadmin:
networks:
  postgres:
    driver: bridge
  backend:
    driver: bridge
