spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:users}
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

app:
  jwtSecret: SecretKey
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 1200000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
rabbitmq:
  exchanges:
    users: users.exchange
  queues:
    payment: payment.queue
    transaction: transaction.queue
  routing-keys:
    users-payment: users.payment.routing-key
    users-transaction: users.transaction.routing-key
