spring:

  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
  mail:
      protocol: smtp
      host: smtp.mailtrap.io
      port: 2525
      username: a21f2f1308ac72
      password: c4a7231f34f319
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.yuincts.mongodb.net/?retryWrites=true&w=majority
      database: notification
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true


rabbitmq:
  exchanges:
    notification: notification.exchange
  queues:
    notification: notification.queue
    email: email.queue
  routing-keys:
    notification: notification.routing-key
    email: email.routing-key