apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions
  labels:
    app: transactions
spec:
  replicas: 1
  template:
    metadata:
      name: transactions
      labels:
        app: transactions
    spec:
      containers:
        - name: transactions
          image: kastourik12/transactions-microservice:latest
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 8082
          envFrom:
            - configMapRef:
                name: transactions-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: transactions
