apiVersion: v1
kind: Secret
metadata:
  name: go-api-secret
type: Opaque
data:
  PAYPAL_CLIENT_ID: QVhxY1BZMHRRM0o2ek50amFHWHlKbnVVZDVFMk1iQkVoXzZDRDF4YkNjVEs5X0lESEtIU0xZUFdISWJtQXdBV1ExMw==
  PAYPAL_CLIENT_SECRET: RUNHUVpKMWFLLWRTQ2dIS0Z4MmtsMm95aXpENFp1T3RUZDhJV1ZQVmEzbjlZZ0pXSEFaMzVUTzVWWW5RSGpjNmZhRzZiblhUSGtsdnprN00=
