spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:payments}
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://localhost:9411
go:
  api:
    host: ${GO_API_HOST:localhost}
    port: ${GO_API_PORT:9090}
eureka:
  instance:
    hostname: localhost
  register-with-eureka: true
  fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
rabbitmq:
  exchanges:
    users: users.exchange
    notification: notification.exchange
  routing-keys:
    users: users.payment.routing-key
    notification: notification.routing-key
