spring:
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
  mail:
    protocol: smtp
    host: smtp.mailtrap.io
    port: 2525
    username: a21f2f1308ac72
    password: c4a7231f34f319
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://test:}
      database: products
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
rabbitmq:
  exchanges:
    products: products.exchange
  queues:
    products: products.queue
    email: email.queue
  routing-keys:
    products: products.routing-key
    email: email.routing-key