server:
  port: 8083
spring:
  application:
    name: transaction
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:transactions}
    username: ${POSTGRES_USER:test}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
rabbitmq:
  exchanges:
    transaction: transaction.exchange
    notification: notification.exchange
  queues:
    transaction: transaction.queue
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
    users-transaction: users.transaction.routing-key

